[package]
name = "hershey_viewer"
version = "0.1.0"
edition = "2018"

[dependencies]
# minifb = "0.24"
winit = "0.29.10"
softbuffer = "0.4.1"
# nanorand = "0.6.1"
hershey_reader = { path = "../hershey_reader" }
